import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import '@fortawesome/fontawesome-free/css/all.min.css';
import './ant.css';

import Navbar from '@/components/layout/navbar';
import Sidebar from '@/components/layout/sidebar';
import AntdProvider from '@/lib/context/antd-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '智能会计教学平台',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full flex text-blueGray-700 antialiased`}>
        <AntdProvider>
          <Sidebar />
          <div className=" flex-1 relative bg-blueGray-100 h-full flex flex-col">
            <Navbar />
            {children}
          </div>
        </AntdProvider>
      </body>
    </html>
  );
}
